server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/notevault?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Pass123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:y9Vx2Q7mLkF8sZcD4nPqWJr0tY6bE3H1aU9XvR5GkM2Np8QsT7wCjL0fZxA4Bv6HdKp3Lm9R2W8XcY1TgU5N0Q==}
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:310340156995-j3qqdmkg8319i7c4r1d9sj1nqlpbgana.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

aes.secret=${AES_SECRET_KEY:V3ZrY1h4Y2V5bXJ4c3Z4Z3J0c2FzZGZnaGprbG1ub3BxcnN0dXZ3eA==}

gemini.api.key=${GEMINI_API_KEY:AIzaSyDoO5Bj-zT8Gy2n62Po68vRH1kvBPCFvCw}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}

app.frontend.url=http://localhost:5173

recycle.bin.auto-delete.days=30

spring.quartz.job-store-type=memory

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized
